import type { Metadata } from "next";
import "./globals.css";
//import { Roboto } from "next/font/google";

export const metadata: Metadata = {
	title: "Fly Serv",
	description: "Generated by create next app",
	icons: {
		icon: "butterfly.svg",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
